pipeline {
    agent any

    tools {
        // Use the configured Node.js version
        nodejs 'nodejs_16'
    }

    stages {
        stage('Setup') {
            steps {
                script {
                    // Verify Node and NPM versions
                    sh 'node -v'
                    sh 'npm -v'
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    // Change directory to backend and install dependencies using npm ci
                    dir('backend') {
                        sh 'npm ci'
                    }
                }
            }
        }

        // Uncomment if build step is needed
        // stage('Build') {
        //     steps {
        //         script {
        //             // Build the project
        //             sh 'npm run build'
        //         }
        //     }
        // }

        stage('Test') {
            steps {
                script {
                    // Run tests from the backend directory
                    dir('backend') {
                        sh 'npm test'
                    }
                }
            }
        }
        
        stage('Docker') {
            steps {
                script {
                    dir('backend'){
                    // Define the Docker image name and tag
                    def imageName = "workingblog"
                    def imageTag = "latest"

                    // Build the Docker image
                    sh "docker build -t suarim/${imageName}:${imageTag} ."
                    sh "echo docker build success"

                    // Log in to Docker Hub or another registry
                    sh "echo qwerty123@@ | docker login -u suarim --password-stdin"

                    // Push the Docker image to the repository
                    sh "docker push suarim/${imageName}:${imageTag}"
                    }
                }
            }
        }

        stage('Container') {
            steps {
                dir('backend'){
                script {
                    sh 'docker run -d -p 4000:4000 suarim/workingblog:latest'
                }
                }
            }
        }
    }
}
